name: showroom_scanner
description: Showroom scanner app for quotes and barcode scanning.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.6.0
  csv: ^6.0.0
  file_picker: ^8.3.7
  path: ^1.9.1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  http: ^1.2.0
  mobile_scanner: ^7.1.4
  excel: ^4.0.6
  unorm_dart: ^0.3.2
  diacritic: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/products.csv
    - assets/data/customers.csv
    - assets/data/customer_walk_order.csv
    - assets/data/product_type_buckets.json
    - assets/sounds/good_scan.mp3
    - assets/sounds/good_scan2.mp3
    - assets/sounds/error_scan.mp3
